# Generated by Django 3.2.9 on 2021-11-29 11:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('postApp', '0002_commentmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyusermodel',
            name='comapny_id',
        ),
        migrations.AddField(
            model_name='companyusermodel',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postmodel',
            name='university_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='postApp.universitymodel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='companyusermodel',
            name='company_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postApp.companymodel'),
        ),
    ]
