# Generated by Django 3.2.9 on 2021-12-01 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postApp', '0004_commentmodel_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='universitymodel',
            name='logo',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
