# Generated by Django 3.2.9 on 2021-12-02 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('postApp', '0005_universitymodel_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='company_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='postApp.companymodel'),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='university_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='postApp.universitymodel'),
        ),
    ]
