# Generated by Django 3.2.9 on 2021-12-02 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postApp', '0006_auto_20211202_0627'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmaterialmodel',
            name='material_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='postmaterialmodel',
            name='material',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
