# Generated by Django 3.2.9 on 2021-12-02 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postApp', '0007_auto_20211202_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmaterialmodel',
            name='material_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='postmaterialmodel',
            unique_together={('material_id', 'post_id')},
        ),
    ]
