# Generated by Django 3.2.9 on 2021-11-06 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='alumni',
            field=models.BooleanField(null=True),
        ),
    ]
