# Generated by Django 3.2.9 on 2021-12-02 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authApp', '0004_auto_20211115_1813'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatModel',
            fields=[
                ('chat_id', models.AutoField(primary_key=True, serialize=False)),
                ('from_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_from_id', to='authApp.usermodel')),
                ('to_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_to_id', to='authApp.usermodel')),
            ],
            options={
                'unique_together': {('from_id', 'to_id', 'chat_id')},
            },
        ),
        migrations.CreateModel(
            name='MessageModel',
            fields=[
                ('timestamp', models.BigIntegerField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('chat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatApp.chatmodel')),
                ('from_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_from_id', to='authApp.usermodel')),
                ('to_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_to_id', to='authApp.usermodel')),
            ],
        ),
    ]
