# Generated by Django 3.2.9 on 2021-12-02 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatApp', '0002_auto_20211202_1015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagemodel',
            name='chat_id',
        ),
    ]
