# Generated by Django 3.2.9 on 2021-12-02 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatApp', '0003_remove_messagemodel_chat_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatModel',
        ),
    ]
