# Generated by Django 3.2.9 on 2021-12-02 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0004_auto_20211115_1813'),
        ('chatApp', '0004_delete_chatmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatModel',
            fields=[
                ('chat_id', models.AutoField(primary_key=True, serialize=False)),
                ('from_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_from_id', to='authApp.usermodel')),
                ('to_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_to_id', to='authApp.usermodel')),
            ],
        ),
        migrations.AddField(
            model_name='messagemodel',
            name='chat_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='chatApp.chatmodel'),
            preserve_default=False,
        ),
    ]
